version: 2

sources:
    - name: airbnb
      schema: raw
      tables:
        - name: litings
          identifier: raw_listings

        - name: hosts
          identifier: raw_hosts

        - name: reviews
          identifier: raw_reviews

        
